In [3]:
import torch

In [4]:
torch.empty(5,3)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [5]:
torch.rand(5,3)

tensor([[0.7178, 0.0943, 0.9869],
        [0.5790, 0.9639, 0.7871],
        [0.9866, 0.0744, 0.0626],
        [0.7637, 0.6454, 0.9932],
        [0.6864, 0.1867, 0.0661]])

In [6]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x = torch.zeros(5,3)

In [8]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
x.type

<function Tensor.type>

In [10]:
x.dtype

torch.float32

In [11]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [25]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [30]:
x = torch.rand_like(x,dtype=torch.float)
x

tensor([[0.0973, 0.9636, 0.0220],
        [0.0774, 0.5849, 0.5398],
        [0.7931, 0.1740, 0.4892],
        [0.6696, 0.1470, 0.8457],
        [0.1220, 0.0871, 0.4244]])

In [31]:
x.size()

torch.Size([5, 3])

In [32]:
y = torch.rand(5,3)

In [33]:
y

tensor([[0.9706, 0.0975, 0.8280],
        [0.1070, 0.8733, 0.5320],
        [0.3528, 0.6038, 0.3970],
        [0.1006, 0.9064, 0.0180],
        [0.8224, 0.4002, 0.3973]])

In [34]:
x +y

tensor([[1.0679, 1.0611, 0.8500],
        [0.1844, 1.4582, 1.0718],
        [1.1459, 0.7778, 0.8862],
        [0.7703, 1.0533, 0.8637],
        [0.9444, 0.4873, 0.8217]])

In [35]:
torch.add(x,y)

tensor([[1.0679, 1.0611, 0.8500],
        [0.1844, 1.4582, 1.0718],
        [1.1459, 0.7778, 0.8862],
        [0.7703, 1.0533, 0.8637],
        [0.9444, 0.4873, 0.8217]])

In [37]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[1.0679, 1.0611, 0.8500],
        [0.1844, 1.4582, 1.0718],
        [1.1459, 0.7778, 0.8862],
        [0.7703, 1.0533, 0.8637],
        [0.9444, 0.4873, 0.8217]])

In [38]:
y.add_(x)
y

tensor([[1.0679, 1.0611, 0.8500],
        [0.1844, 1.4582, 1.0718],
        [1.1459, 0.7778, 0.8862],
        [0.7703, 1.0533, 0.8637],
        [0.9444, 0.4873, 0.8217]])

In [39]:
x

tensor([[0.0973, 0.9636, 0.0220],
        [0.0774, 0.5849, 0.5398],
        [0.7931, 0.1740, 0.4892],
        [0.6696, 0.1470, 0.8457],
        [0.1220, 0.0871, 0.4244]])

In [40]:
x


tensor([[0.0973, 0.9636, 0.0220],
        [0.0774, 0.5849, 0.5398],
        [0.7931, 0.1740, 0.4892],
        [0.6696, 0.1470, 0.8457],
        [0.1220, 0.0871, 0.4244]])

In [42]:
x[:,1:]

tensor([[0.9636, 0.0220],
        [0.5849, 0.5398],
        [0.1740, 0.4892],
        [0.1470, 0.8457],
        [0.0871, 0.4244]])

In [45]:
x = torch.randn(4,4)
y = x.reshape(2,8)
y

tensor([[-0.2648, -1.7337,  0.3081,  0.2916,  1.0064, -0.5937,  0.6856,  0.7685],
        [-1.1100,  0.0162,  1.3621, -0.7600,  1.1492,  2.6333, -0.8367, -0.1553]])

In [46]:
x = torch.randn(1)
x

tensor([-0.7932])

In [47]:
x.data

tensor([-0.7932])

In [48]:
x.item()


-0.7932124137878418

In [49]:
y

tensor([[-0.2648, -1.7337,  0.3081,  0.2916,  1.0064, -0.5937,  0.6856,  0.7685],
        [-1.1100,  0.0162,  1.3621, -0.7600,  1.1492,  2.6333, -0.8367, -0.1553]])

In [50]:
y.transpose(1,0)

tensor([[-0.2648, -1.1100],
        [-1.7337,  0.0162],
        [ 0.3081,  1.3621],
        [ 0.2916, -0.7600],
        [ 1.0064,  1.1492],
        [-0.5937,  2.6333],
        [ 0.6856, -0.8367],
        [ 0.7685, -0.1553]])

In [51]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [52]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [53]:
a

tensor([1., 1., 1., 1., 1.])

In [54]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
a

array([1., 1., 1., 1., 1.])

In [55]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [57]:
np.add(a,1,out=a)

array([2., 2., 2., 2., 2.])

In [58]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [59]:
a = a +1
a

array([3., 3., 3., 3., 3.])

In [60]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [61]:
a


array([3., 3., 3., 3., 3.])

In [62]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [63]:
b = torch.from_numpy(a)
b


tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [68]:
np.add(a,1,out=a)

array([2., 2., 2., 2., 2.])

In [69]:
b


tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [70]:
torch.cuda.is_available()

False

In [71]:
nvidia-smi

NameError: name 'nvidia' is not defined

In [74]:
cuda_visible_devices=0

In [75]:
torch.cuda.is_available()

False

In [76]:
x

tensor([-0.7932])

In [77]:
x.cuda()

RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

In [1]:
import os
import numpy as np
import torch

torch.cuda.is_available()

True

In [17]:
N, D_in,H,D_out = 64,1000,100,10
# 随机创建一些训练数据
x = torch.randn(N, D_in)
y = torch.randn(N,D_out)

w1 = torch.randn(D_in,H)
w2 = torch.randn(H, D_out)

learning_rate = 1e-6
for it in range(500):
    # Forward pass
    h = x.mm(w1) # N*H
    h_relu = h.clamp(min=0) # N*H
    y_pred = h_relu.mm(w2) # N*D_out
    
    # compute loss
    loss = np.square(y_pred-y).sum().item()
    print(it,loss)
    
    # Backward pass
    # compute the gradient
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 =h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h<0] = 0
    grad_w1 = x.t().mm(grad_h)
    
    # update weight of w1 and w2
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    
    
    
    

0 37947000.0
1 39459980.0
2 43855320.0
3 41846364.0
4 30120704.0
5 16027488.0
6 7162514.0
7 3359399.0
8 1927278.0
9 1338941.0
10 1040842.625
11 853140.375
12 716818.6875
13 610181.0
14 523906.53125
15 452785.84375
16 393460.28125
17 343549.53125
18 301317.6875
19 265395.09375
20 234634.140625
21 208130.765625
22 185210.421875
23 165314.671875
24 147961.9375
25 132768.125
26 119414.859375
27 107657.359375
28 97269.71875
29 88063.328125
30 79886.640625
31 72556.46875
32 66013.1875
33 60160.71875
34 54914.14453125
35 50201.25
36 45964.3125
37 42148.04296875
38 38703.7265625
39 35586.03125
40 32761.578125
41 30199.30859375
42 27878.61328125
43 25765.458984375
44 23837.40234375
45 22077.23828125
46 20467.46484375
47 18994.373046875
48 17643.646484375
49 16404.30859375
50 15264.6982421875
51 14216.4306640625
52 13251.1318359375
53 12361.26953125
54 11541.4375
55 10784.2685546875
56 10084.4765625
57 9436.626953125
58 8836.1015625
59 8279.548828125
60 7763.08740234375
61 7283.44482421875
62 68

385 0.012287657707929611
386 0.011870144866406918
387 0.011467319913208485
388 0.01108665019273758
389 0.010715019889175892
390 0.010353736579418182
391 0.010012085549533367
392 0.009686363860964775
393 0.009359030984342098
394 0.009043112397193909
395 0.00874789897352457
396 0.008454421535134315
397 0.008179723285138607
398 0.007911289110779762
399 0.007649085018783808
400 0.007392858155071735
401 0.007153566926717758
402 0.006926096044480801
403 0.0067006382159888744
404 0.006475954316556454
405 0.006272772327065468
406 0.006064959801733494
407 0.005869001615792513
408 0.005683434661477804
409 0.0055016446858644485
410 0.005322807468473911
411 0.005155643448233604
412 0.004987324122339487
413 0.004830278921872377
414 0.004676001146435738
415 0.004529751371592283
416 0.004382905084639788
417 0.004247037693858147
418 0.00411306694149971
419 0.003983974922448397
420 0.0038630510680377483
421 0.0037427651695907116
422 0.003628444392234087
423 0.003518868237733841
424 0.003408035496249795

In [50]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
y = w*x+b
print(y)
y.backward()
print(x.grad)
print(w.grad)
print(b.grad)

tensor(5., grad_fn=<AddBackward0>)
tensor(2.)
tensor(1.)
tensor(1.)


In [51]:
N, D_in,H,D_out = 64,1000,100,10
# 随机创建一些训练数据
x = torch.randn(N, D_in)
y = torch.randn(N,D_out)

w1 = torch.randn(D_in,H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)

learning_rate = 1e-6
for it in range(500):
    # Forward pass
#     h = x.mm(w1) # N*H
#     h_relu = h.clamp(min=0) # N*H
#     y_pred = h_relu.mm(w2) # N*D_out
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    # compute loss
    loss = (y_pred-y).pow(2).sum()  # computation graph
    print(it,loss.item())
    
    # Backward pass
    loss.backward()


    
    # update weight of w1 and w2
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
    w1.grad.zero_()
    w2.grad.zero_()

0 29166854.0
1 31334746.0
2 43075964.0
3 57439448.0
4 59300824.0
5 38722752.0
6 15093683.0
7 4540087.5
8 1828968.5
9 1150358.375
10 895820.8125
11 743962.125
12 630860.625
13 540238.5625
14 465913.25
15 404314.3125
16 352799.03125
17 309353.0
18 272415.65625
19 240814.71875
20 213628.171875
21 190080.734375
22 169607.921875
23 151750.5
24 136114.875
25 122384.3203125
26 110285.8125
27 99579.265625
28 90087.5546875
29 81643.015625
30 74109.4453125
31 67388.5546875
32 61373.38671875
33 55971.71875
34 51109.74609375
35 46727.05078125
36 42769.921875
37 39196.8828125
38 35968.13671875
39 33038.578125
40 30374.19140625
41 27949.84375
42 25738.814453125
43 23720.771484375
44 21879.12890625
45 20195.69140625
46 18655.650390625
47 17242.552734375
48 15946.53125
49 14757.1650390625
50 13664.7421875
51 12660.51953125
52 11736.31640625
53 10885.4677734375
54 10101.7275390625
55 9379.083984375
56 8712.607421875
57 8097.76513671875
58 7530.0458984375
59 7005.251953125
60 6519.88720703125
61 6070.74

408 0.00045905340812169015
409 0.00044712406815961003
410 0.0004352443211246282
411 0.0004239724366925657
412 0.0004136207571718842
413 0.00040260283276438713
414 0.00039207839290611446
415 0.00038237296394072473
416 0.0003731157921720296
417 0.00036280302447266877
418 0.00035420365747995675
419 0.0003452099044807255
420 0.0003367123717907816
421 0.000328605470713228
422 0.00032010546419769526
423 0.0003118645690847188
424 0.0003042615717276931
425 0.00029670263756997883
426 0.0002901267434936017
427 0.0002828676369972527
428 0.0002764873206615448
429 0.00027041338034905493
430 0.0002641350438352674
431 0.00025881524197757244
432 0.00025170124717988074
433 0.00024643796496093273
434 0.000241316098254174
435 0.0002359942882321775
436 0.00023113260976970196
437 0.00022618456569034606
438 0.00022125142277218401
439 0.0002162035380024463
440 0.00021220400230959058
441 0.00020712046534754336
442 0.00020287311053834856
443 0.00019928766414523125
444 0.00019486223754938692
445 0.0001913657179

In [45]:
N, D_in,H,D_out = 64,1000,100,10
# 随机创建一些训练数据
x = torch.randn(N, D_in)
y = torch.randn(N,D_out)

w1 = torch.randn(D_in,H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)

learning_rate = 1e-6

# Forward pass
#     h = x.mm(w1) # N*H
#     h_relu = h.clamp(min=0) # N*H
#     y_pred = h_relu.mm(w2) # N*D_out
y_pred = x.mm(w1).clamp(min=0).mm(w2)

# compute loss
loss = (y_pred-y).pow(2).sum()  # computation graph
print(it,loss.item())

# Backward pass
loss.backward()

499 43536352.0


In [67]:
w1.grad


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [77]:
import torch.nn as nn

N, D_in,H,D_out = 64,1000,100,10
# 随机创建一些训练数据
x = torch.randn(N, D_in)
y = torch.randn(N,D_out)

# w1 = torch.randn(D_in,H, requires_grad=True)
# w2 = torch.randn(H, D_out, requires_grad=True)
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H, bias=False),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out, bias=False),
)

torch.nn.init.normal_(model[0].weight)
torch.nn.init.normal_(model[2].weight)

# model = model.cuda()

loss_fn = nn.MSELoss(reduction='sum')
# learning_rate = 1e-4
# optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

learning_rate = 1e-6
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for it in range(500):
    # Forward pass
    y_pred = model(x)
    
    # compute loss
    loss = loss_fn(y_pred , y)  # computation graph
    print(it,loss.item())
    
    optimizer.zero_grad()
    
    # Backward pass
    loss.backward()

    
    # update weight of w1 and w2
    optimizer.step()
    

0 31635860.0
1 27107598.0
2 26624052.0
3 25516990.0
4 21934362.0
5 15997405.0
6 10196501.0
7 5922331.5
8 3411336.25
9 2061038.125
10 1355400.75
11 970904.375
12 745685.5625
13 600942.0
14 499663.6875
15 423677.4375
16 363781.75
17 315017.3125
18 274496.78125
19 240400.90625
20 211410.53125
21 186581.78125
22 165234.6875
23 146772.015625
24 130730.34375
25 116727.71875
26 104454.34375
27 93672.390625
28 84176.8984375
29 75792.5078125
30 68363.8125
31 61766.6484375
32 55900.8984375
33 50669.14453125
34 45993.62109375
35 41809.1875
36 38056.09765625
37 34683.96484375
38 31647.845703125
39 28911.521484375
40 26441.962890625
41 24208.453125
42 22187.03125
43 20354.859375
44 18691.955078125
45 17181.169921875
46 15807.70703125
47 14556.7890625
48 13416.8837890625
49 12376.8798828125
50 11427.0224609375
51 10557.6943359375
52 9761.72265625
53 9032.5869140625
54 8363.5927734375
55 7749.2177734375
56 7184.732421875
57 6665.8671875
58 6188.60107421875
59 5748.99609375
60 5343.78564453125
61 4969

409 0.0004954725154675543
410 0.00048245140351355076
411 0.00046945252688601613
412 0.0004586777067743242
413 0.0004463146033231169
414 0.00043410007492639124
415 0.00042413637856952846
416 0.00041336860158480704
417 0.000402922451030463
418 0.0003931753453798592
419 0.00038291336386464536
420 0.00037356687244027853
421 0.00036517129046842456
422 0.00035697437124326825
423 0.00034852378303185105
424 0.0003398479602765292
425 0.00033279391936957836
426 0.0003253202303312719
427 0.0003171775315422565
428 0.00030938367126509547
429 0.0003025399928446859
430 0.0002965499006677419
431 0.0002906280860770494
432 0.0002833210164681077
433 0.0002767696569208056
434 0.00027114301337860525
435 0.0002657551085576415
436 0.00025988442939706147
437 0.0002543682639952749
438 0.00024891982320696115
439 0.00024326902348548174
440 0.00023853172024246305
441 0.00023425246763508767
442 0.00022850178356748074
443 0.00022395812266040593
444 0.0002191413368564099
445 0.00021473973174579442
446 0.000210353347

In [69]:
model[0].weight

Parameter containing:
tensor([[ 0.8084, -0.6575, -0.3067,  ...,  1.7378,  1.9232, -0.3874],
        [ 0.8342, -0.9789,  0.5655,  ..., -0.2236, -0.1784,  0.9570],
        [-1.1518, -1.3509, -2.8544,  ..., -1.1010,  0.8274,  1.9028],
        ...,
        [ 0.8895, -1.1872, -1.3862,  ...,  1.6319,  0.2891, -0.0971],
        [-2.0606,  1.9076, -0.2625,  ..., -1.3040, -0.5768, -0.6194],
        [ 2.4754,  0.0963, -0.0172,  ...,  1.0128,  0.3246,  1.3429]],
       requires_grad=True)

In [81]:
import torch.nn as nn

N, D_in,H,D_out = 64,1000,100,10
# 随机创建一些训练数据
x = torch.randn(N, D_in)
y = torch.randn(N,D_out)

class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H, bias=False)
        self.linear2 = torch.nn.Linear(H, D_out, bias=False)
        
    def forward(self, x):
        y_pred = self.linear2(self.linear1(x).clamp(min=0))
        return y_pred

model = TwoLayerNet(D_in, H, D_out)

# model = torch.nn.Sequential(
#     torch.nn.Linear(D_in, H, bias=False),
#     torch.nn.ReLU(),
#     torch.nn.Linear(H, D_out, bias=False),
# )

# torch.nn.init.normal_(model[0].weight)
# torch.nn.init.normal_(model[2].weight)

# model = model.cuda()

loss_fn = nn.MSELoss(reduction='sum')
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for it in range(500):
    # Forward pass
    y_pred = model(x)
    
    # compute loss
    loss = loss_fn(y_pred , y)  # computation graph
    print(it,loss.item())
    
    optimizer.zero_grad()
    
    # Backward pass
    loss.backward()

    
    # update weight of w1 and w2
    optimizer.step()

RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'mat2'